### ISSUE TITLE
Update for React 16

### ISSUE THREAD

**Issue by gaearon** [elijahmanor/react-file-size#7]
We worked hard to reduce the file size in React 16. It would be amazing to have the chart updated, as people keep referring to this website, and currently it is misleading.

**Comment by elijahmanor** [comment]
Thanks for the feedback. I have updated the charts and have structured the code to understand the different filenames pre and post version 16. http://elijahmanor.com/react-file-size/

**Comment by gaearon** [comment]
Thanks!
